/**
 * @fileOverview Defines all Redux action types used to modify the state of the application
 * @author Jonah Joughin
 */

const ACTION_TYPES = {
  // Map Actions
  SET_MAP_VIEW_STATE: "SET_MAP_VIEW_STATE",
  // Observations Actions
  SET_OBSERVATIONS: "SET_OBSERVATIONS",
  SET_CPU_FILTERED_OBSERVATIONS: "SET_CPU_FILTERED_OBSERVATIONS",
  SET_FILTERED_OBSERVATIONS: "SET_FILTERED_OBSERVATIONS",
  SET_HOVERED_OBSERVATION: "SET_HOVERED_OBSERVATION",
  // General Filter Actions
  // Used to modify set of filters in use
  ADD_FILTERS: "ADD_FILTERS",
  SET_FILTERS: "SET_FILTERS",
  // Discrete Filter Actions
  SET_SELECTED_DISCRETE_FILTER: "SET_SELECTED_DISCRETE_FILTER",
  // Geo Filter Actions
  SET_FEATURE_COLLECTION_GEO_FILTER: "SET_FEATURE_COLLECTION_GEO_FILTER",
  SET_DRAW_MODE_GEO_FILTER: "SET_DRAW_MODE_GEO_FILTER",
  // Range Filter Actions
  SET_SELECTED_RANGE_FILTER: "SET_SELECTED_RANGE_FILTER",
  REQUEST_FULL_FILTER_EVALUATION_ON_CPU: "REQUEST_FULL_FILTER_EVALUATION_ON_CPU"
}

export default ACTION_TYPES;
